[book]
title = "logv"
description = "Information and manuals about logv"
authors = [
    "Mohammed R.W. Neundorf [https://github.com/naxmefy]"
]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[build]
extra-watch-dirs = [
    "assets"
]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
mathjax-support = true
cname = "logv.nax.me"
site-url = "/"
input-404 = "not-found.md"
additional-js = [
    "assets/js/mermaid.min.js",
    "assets/js/mermaid-init.js"
]
git-repository-url = "https://github.com/naxmefy/logv/tree/main/book"
edit-url-template = "https://github.com/naxmefy/logv/edit/main/book/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
